stages:
  - guideline
  - test

image: node:latest

before_script:
  - npm install

cache:
  paths:
  - node_modules/

lint:
  stage: guideline
  script:
   - npm run lint

flow:
  stage: guideline
  script:
   - npm run flow

test:
  stage: test
  script:
   - npm run test

