stages:
  - lint
  - flow
  - test

image: node:latest

before_script:
  - npm install

cache:
  paths:
  - node_modules/

lint:
  stage: lint
  script:
   - npm run lint

flow:
  stage: flow
  script:
   - flow

test:
  stage: test
  script:
   - npm run test

