stages:
  - guideline
  - test
  - publish

image: node:latest

before_script:
  - npm install

cache:
  paths:
  - node_modules/

# lint:
#   stage: guideline
#   script:
#    - npm run lint

flow:
  stage: guideline
  script:
   - npm run flow

test:
  stage: test
  script:
   - npm run test

publish:
  stage: publish
  artifacts:
    paths:
    - public
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    - cat ~/.npmrc
    - npm run build
    - npm publish
  only:
    - master
