stages:
  - guideline
  - test
  - deploy

image: node:latest

before_script:
  - npm install

cache:
  paths:
  - node_modules/

# lint:
#   stage: guideline
#   script:
#    - npm run lint

flow:
  stage: guideline
  script:
   - npm run flow

test:
  stage: test
  script:
   - npm run coverage

deploy:
  stage: deploy
  environment: docs
  artifacts:
    paths:
      - public
  script:
    - npm run build:docs
    - npm run coverage
    - mkdir public
    - cp -R static/* public
    - mv coverage public
  only:
    - master

publish:
  stage: deploy
  environment: production
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    - npm run build
    - npm publish
  only:
    - master
  when: manual
