// flow-typed signature: b50fd6558d393953d3990e68346d0acd
// flow-typed version: <<STUB>>/csslint_v^1.0.5/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csslint/dist/cli' {
  declare module.exports: any;
}

declare module 'csslint/dist/csslint-node' {
  declare module.exports: any;
}

declare module 'csslint/dist/csslint' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csslint/dist/cli.js' {
  declare module.exports: $Exports<'csslint/dist/cli'>;
}
declare module 'csslint/dist/csslint-node.js' {
  declare module.exports: $Exports<'csslint/dist/csslint-node'>;
}
declare module 'csslint/dist/csslint.js' {
  declare module.exports: $Exports<'csslint/dist/csslint'>;
}
