// flow-typed signature: c5f0f7aa6748672a0ac038cc8132ac52
// flow-typed version: <<STUB>>/npm-watch_v^0.3.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-watch/cli' {
  declare module.exports: any;
}

declare module 'npm-watch/watch-package' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-watch/cli.js' {
  declare module.exports: $Exports<'npm-watch/cli'>;
}
declare module 'npm-watch/watch-package.js' {
  declare module.exports: $Exports<'npm-watch/watch-package'>;
}
