// flow-typed signature: 30c2b9e6fa5e5d4afed2f1c362fb418a
// flow-typed version: <<STUB>>/strip-loader_v^0.1.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'strip-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'strip-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'strip-loader/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'strip-loader/lib/index.js' {
  declare module.exports: $Exports<'strip-loader/lib/index'>;
}
