// flow-typed signature: 39a91a90d7ede33b556c81293cfe8308
// flow-typed version: <<STUB>>/tern-react_v^0.1.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tern-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tern-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tern-react/demos/acorn-jsx' {
  declare module.exports: any;
}

declare module 'tern-react/demos/defs/browser.json' {
  declare module.exports: any;
}

declare module 'tern-react/demos/defs/ecma5.json' {
  declare module.exports: any;
}

declare module 'tern-react/demos/defs/jquery.json' {
  declare module.exports: any;
}

declare module 'tern-react/react' {
  declare module.exports: any;
}

declare module 'tern-react/scripts/git-tag' {
  declare module.exports: any;
}

declare module 'tern-react/test/all' {
  declare module.exports: any;
}

declare module 'tern-react/test/completion/JSX' {
  declare module.exports: any;
}

declare module 'tern-react/test/completion/React' {
  declare module.exports: any;
}

declare module 'tern-react/test/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tern-react/demos/acorn-jsx.js' {
  declare module.exports: $Exports<'tern-react/demos/acorn-jsx'>;
}
declare module 'tern-react/demos/defs/browser.json.js' {
  declare module.exports: $Exports<'tern-react/demos/defs/browser.json'>;
}
declare module 'tern-react/demos/defs/ecma5.json.js' {
  declare module.exports: $Exports<'tern-react/demos/defs/ecma5.json'>;
}
declare module 'tern-react/demos/defs/jquery.json.js' {
  declare module.exports: $Exports<'tern-react/demos/defs/jquery.json'>;
}
declare module 'tern-react/react.js' {
  declare module.exports: $Exports<'tern-react/react'>;
}
declare module 'tern-react/scripts/git-tag.js' {
  declare module.exports: $Exports<'tern-react/scripts/git-tag'>;
}
declare module 'tern-react/test/all.js' {
  declare module.exports: $Exports<'tern-react/test/all'>;
}
declare module 'tern-react/test/completion/JSX.js' {
  declare module.exports: $Exports<'tern-react/test/completion/JSX'>;
}
declare module 'tern-react/test/completion/React.js' {
  declare module.exports: $Exports<'tern-react/test/completion/React'>;
}
declare module 'tern-react/test/util.js' {
  declare module.exports: $Exports<'tern-react/test/util'>;
}
