// flow-typed signature: 49ee7ef158e56ebb3f5668482a68b8a5
// flow-typed version: <<STUB>>/@material/button_v^0.25.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/button' {
  declare module.exports: any;
}
