// flow-typed signature: 7d1517f81c02772b79770afc6f36055c
// flow-typed version: <<STUB>>/@material/button_v^0.34.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/button' {
  declare module.exports: any;
}
