// flow-typed signature: e6926ffa811c2173d88f5f5aa2530624
// flow-typed version: <<STUB>>/@material/card_v^0.34.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/card'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/card' {
  declare module.exports: any;
}
