// flow-typed signature: a93a2144b2a3c5aea46cee84103e0e47
// flow-typed version: <<STUB>>/@material/elevation_v^0.28.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/elevation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/elevation' {
  declare module.exports: any;
}
