// flow-typed signature: 1af4bab0d20b1250f6fa1200d25197b0
// flow-typed version: <<STUB>>/@material/elevation_v^0.34.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/elevation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/elevation' {
  declare module.exports: any;
}
