// flow-typed signature: 1043b9315e0a119ef34e0b4cbeb2d3e7
// flow-typed version: <<STUB>>/@material/elevation_v^0.25.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/elevation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/elevation' {
  declare module.exports: any;
}
