// flow-typed signature: e72d959b23360394dab4d34e9cd128ab
// flow-typed version: <<STUB>>/@material/fab_v^0.25.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/fab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/fab' {
  declare module.exports: any;
}
