// flow-typed signature: 3d01d3e5f476ca307997c1a9fc0ff742
// flow-typed version: <<STUB>>/@material/fab_v^0.28.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/fab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/fab' {
  declare module.exports: any;
}
