// flow-typed signature: 2185b09a161a9e50b7cc9b5535bb6bf7
// flow-typed version: <<STUB>>/@material/fab_v^0.34.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/fab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/fab' {
  declare module.exports: any;
}
