// flow-typed signature: 48acf193601b9ae988a86a44a40a7745
// flow-typed version: <<STUB>>/@material/floating-label_v^0.34.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/floating-label'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/floating-label' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/floating-label/adapter' {
  declare module.exports: any;
}

declare module '@material/floating-label/constants' {
  declare module.exports: any;
}

declare module '@material/floating-label/dist/mdc.floatingLabel' {
  declare module.exports: any;
}

declare module '@material/floating-label/dist/mdc.floatingLabel.min' {
  declare module.exports: any;
}

declare module '@material/floating-label/foundation' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/floating-label/adapter.js' {
  declare module.exports: $Exports<'@material/floating-label/adapter'>;
}
declare module '@material/floating-label/constants.js' {
  declare module.exports: $Exports<'@material/floating-label/constants'>;
}
declare module '@material/floating-label/dist/mdc.floatingLabel.js' {
  declare module.exports: $Exports<'@material/floating-label/dist/mdc.floatingLabel'>;
}
declare module '@material/floating-label/dist/mdc.floatingLabel.min.js' {
  declare module.exports: $Exports<'@material/floating-label/dist/mdc.floatingLabel.min'>;
}
declare module '@material/floating-label/foundation.js' {
  declare module.exports: $Exports<'@material/floating-label/foundation'>;
}
declare module '@material/floating-label/index' {
  declare module.exports: $Exports<'@material/floating-label'>;
}
declare module '@material/floating-label/index.js' {
  declare module.exports: $Exports<'@material/floating-label'>;
}
