// flow-typed signature: c79a7bfeed8a9dbceafb7e18f643928d
// flow-typed version: <<STUB>>/@material/icon-toggle_v^0.25.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/icon-toggle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/icon-toggle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/icon-toggle/adapter' {
  declare module.exports: any;
}

declare module '@material/icon-toggle/constants' {
  declare module.exports: any;
}

declare module '@material/icon-toggle/dist/mdc.iconToggle' {
  declare module.exports: any;
}

declare module '@material/icon-toggle/dist/mdc.iconToggle.min' {
  declare module.exports: any;
}

declare module '@material/icon-toggle/foundation' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/icon-toggle/adapter.js' {
  declare module.exports: $Exports<'@material/icon-toggle/adapter'>;
}
declare module '@material/icon-toggle/constants.js' {
  declare module.exports: $Exports<'@material/icon-toggle/constants'>;
}
declare module '@material/icon-toggle/dist/mdc.iconToggle.js' {
  declare module.exports: $Exports<'@material/icon-toggle/dist/mdc.iconToggle'>;
}
declare module '@material/icon-toggle/dist/mdc.iconToggle.min.js' {
  declare module.exports: $Exports<'@material/icon-toggle/dist/mdc.iconToggle.min'>;
}
declare module '@material/icon-toggle/foundation.js' {
  declare module.exports: $Exports<'@material/icon-toggle/foundation'>;
}
declare module '@material/icon-toggle/index' {
  declare module.exports: $Exports<'@material/icon-toggle'>;
}
declare module '@material/icon-toggle/index.js' {
  declare module.exports: $Exports<'@material/icon-toggle'>;
}
