// flow-typed signature: df41573aa811f5f52e45bd267a9dc579
// flow-typed version: <<STUB>>/@material/layout-grid_v^0.24.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/layout-grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/layout-grid' {
  declare module.exports: any;
}
