// flow-typed signature: e75ad3f74e1b322ef38ed797113f7dc4
// flow-typed version: <<STUB>>/@material/line-ripple_v^0.34.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/line-ripple'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/line-ripple' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/line-ripple/adapter' {
  declare module.exports: any;
}

declare module '@material/line-ripple/constants' {
  declare module.exports: any;
}

declare module '@material/line-ripple/dist/mdc.lineRipple' {
  declare module.exports: any;
}

declare module '@material/line-ripple/dist/mdc.lineRipple.min' {
  declare module.exports: any;
}

declare module '@material/line-ripple/foundation' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/line-ripple/adapter.js' {
  declare module.exports: $Exports<'@material/line-ripple/adapter'>;
}
declare module '@material/line-ripple/constants.js' {
  declare module.exports: $Exports<'@material/line-ripple/constants'>;
}
declare module '@material/line-ripple/dist/mdc.lineRipple.js' {
  declare module.exports: $Exports<'@material/line-ripple/dist/mdc.lineRipple'>;
}
declare module '@material/line-ripple/dist/mdc.lineRipple.min.js' {
  declare module.exports: $Exports<'@material/line-ripple/dist/mdc.lineRipple.min'>;
}
declare module '@material/line-ripple/foundation.js' {
  declare module.exports: $Exports<'@material/line-ripple/foundation'>;
}
declare module '@material/line-ripple/index' {
  declare module.exports: $Exports<'@material/line-ripple'>;
}
declare module '@material/line-ripple/index.js' {
  declare module.exports: $Exports<'@material/line-ripple'>;
}
