// flow-typed signature: 32616e2d13b5e7f7822f462bcf3292ac
// flow-typed version: <<STUB>>/@material/list_v^0.25.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/list' {
  declare module.exports: any;
}
