// flow-typed signature: 2610346fec5b5966a064bdf0c610a1eb
// flow-typed version: <<STUB>>/@material/list_v^0.28.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/list' {
  declare module.exports: any;
}
