// flow-typed signature: e1128ed661247a38c821c2e2a1d5c285
// flow-typed version: <<STUB>>/@material/list_v^0.34.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/list' {
  declare module.exports: any;
}
