// flow-typed signature: 72dde7ab5d2b85a2d8e9c1eb000e77e8
// flow-typed version: <<STUB>>/@material/notched-outline_v^0.34.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/notched-outline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/notched-outline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/notched-outline/adapter' {
  declare module.exports: any;
}

declare module '@material/notched-outline/constants' {
  declare module.exports: any;
}

declare module '@material/notched-outline/dist/mdc.notchedOutline' {
  declare module.exports: any;
}

declare module '@material/notched-outline/dist/mdc.notchedOutline.min' {
  declare module.exports: any;
}

declare module '@material/notched-outline/foundation' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/notched-outline/adapter.js' {
  declare module.exports: $Exports<'@material/notched-outline/adapter'>;
}
declare module '@material/notched-outline/constants.js' {
  declare module.exports: $Exports<'@material/notched-outline/constants'>;
}
declare module '@material/notched-outline/dist/mdc.notchedOutline.js' {
  declare module.exports: $Exports<'@material/notched-outline/dist/mdc.notchedOutline'>;
}
declare module '@material/notched-outline/dist/mdc.notchedOutline.min.js' {
  declare module.exports: $Exports<'@material/notched-outline/dist/mdc.notchedOutline.min'>;
}
declare module '@material/notched-outline/foundation.js' {
  declare module.exports: $Exports<'@material/notched-outline/foundation'>;
}
declare module '@material/notched-outline/index' {
  declare module.exports: $Exports<'@material/notched-outline'>;
}
declare module '@material/notched-outline/index.js' {
  declare module.exports: $Exports<'@material/notched-outline'>;
}
