// flow-typed signature: ccc18e834846f10d541a9eb45c86f4d0
// flow-typed version: <<STUB>>/@material/select_v^0.34.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/select/bottom-line/adapter' {
  declare module.exports: any;
}

declare module '@material/select/bottom-line/constants' {
  declare module.exports: any;
}

declare module '@material/select/bottom-line/foundation' {
  declare module.exports: any;
}

declare module '@material/select/bottom-line/index' {
  declare module.exports: any;
}

declare module '@material/select/constants' {
  declare module.exports: any;
}

declare module '@material/select/dist/mdc.select' {
  declare module.exports: any;
}

declare module '@material/select/dist/mdc.select.min' {
  declare module.exports: any;
}

declare module '@material/select/foundation' {
  declare module.exports: any;
}

declare module '@material/select/label/adapter' {
  declare module.exports: any;
}

declare module '@material/select/label/constants' {
  declare module.exports: any;
}

declare module '@material/select/label/foundation' {
  declare module.exports: any;
}

declare module '@material/select/label/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/select/bottom-line/adapter.js' {
  declare module.exports: $Exports<'@material/select/bottom-line/adapter'>;
}
declare module '@material/select/bottom-line/constants.js' {
  declare module.exports: $Exports<'@material/select/bottom-line/constants'>;
}
declare module '@material/select/bottom-line/foundation.js' {
  declare module.exports: $Exports<'@material/select/bottom-line/foundation'>;
}
declare module '@material/select/bottom-line/index.js' {
  declare module.exports: $Exports<'@material/select/bottom-line/index'>;
}
declare module '@material/select/constants.js' {
  declare module.exports: $Exports<'@material/select/constants'>;
}
declare module '@material/select/dist/mdc.select.js' {
  declare module.exports: $Exports<'@material/select/dist/mdc.select'>;
}
declare module '@material/select/dist/mdc.select.min.js' {
  declare module.exports: $Exports<'@material/select/dist/mdc.select.min'>;
}
declare module '@material/select/foundation.js' {
  declare module.exports: $Exports<'@material/select/foundation'>;
}
declare module '@material/select/index' {
  declare module.exports: $Exports<'@material/select'>;
}
declare module '@material/select/index.js' {
  declare module.exports: $Exports<'@material/select'>;
}
declare module '@material/select/label/adapter.js' {
  declare module.exports: $Exports<'@material/select/label/adapter'>;
}
declare module '@material/select/label/constants.js' {
  declare module.exports: $Exports<'@material/select/label/constants'>;
}
declare module '@material/select/label/foundation.js' {
  declare module.exports: $Exports<'@material/select/label/foundation'>;
}
declare module '@material/select/label/index.js' {
  declare module.exports: $Exports<'@material/select/label/index'>;
}
