// flow-typed signature: ed674b4019c74e51a7c128e16ff32d63
// flow-typed version: <<STUB>>/@material/slider_v^0.34.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/slider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/slider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/slider/adapter' {
  declare module.exports: any;
}

declare module '@material/slider/constants' {
  declare module.exports: any;
}

declare module '@material/slider/dist/mdc.slider' {
  declare module.exports: any;
}

declare module '@material/slider/dist/mdc.slider.min' {
  declare module.exports: any;
}

declare module '@material/slider/foundation' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/slider/adapter.js' {
  declare module.exports: $Exports<'@material/slider/adapter'>;
}
declare module '@material/slider/constants.js' {
  declare module.exports: $Exports<'@material/slider/constants'>;
}
declare module '@material/slider/dist/mdc.slider.js' {
  declare module.exports: $Exports<'@material/slider/dist/mdc.slider'>;
}
declare module '@material/slider/dist/mdc.slider.min.js' {
  declare module.exports: $Exports<'@material/slider/dist/mdc.slider.min'>;
}
declare module '@material/slider/foundation.js' {
  declare module.exports: $Exports<'@material/slider/foundation'>;
}
declare module '@material/slider/index' {
  declare module.exports: $Exports<'@material/slider'>;
}
declare module '@material/slider/index.js' {
  declare module.exports: $Exports<'@material/slider'>;
}
