// flow-typed signature: 81326a6b6a0d9779b0bd6be044bbf56c
// flow-typed version: <<STUB>>/@material/switch_v^0.34.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/switch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/switch' {
  declare module.exports: any;
}
