// flow-typed signature: 9799fa7d34c0563c43d780b63678026f
// flow-typed version: <<STUB>>/@material/switch_v^0.28.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/switch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/switch' {
  declare module.exports: any;
}
