// flow-typed signature: 766779878bb8990f8db6f447f40197cf
// flow-typed version: <<STUB>>/@material/textfield_v^0.28.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/textfield'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/textfield' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/textfield/adapter' {
  declare module.exports: any;
}

declare module '@material/textfield/bottom-line/adapter' {
  declare module.exports: any;
}

declare module '@material/textfield/bottom-line/constants' {
  declare module.exports: any;
}

declare module '@material/textfield/bottom-line/foundation' {
  declare module.exports: any;
}

declare module '@material/textfield/bottom-line/index' {
  declare module.exports: any;
}

declare module '@material/textfield/constants' {
  declare module.exports: any;
}

declare module '@material/textfield/dist/mdc.textfield' {
  declare module.exports: any;
}

declare module '@material/textfield/dist/mdc.textfield.min' {
  declare module.exports: any;
}

declare module '@material/textfield/foundation' {
  declare module.exports: any;
}

declare module '@material/textfield/helper-text/adapter' {
  declare module.exports: any;
}

declare module '@material/textfield/helper-text/constants' {
  declare module.exports: any;
}

declare module '@material/textfield/helper-text/foundation' {
  declare module.exports: any;
}

declare module '@material/textfield/helper-text/index' {
  declare module.exports: any;
}

declare module '@material/textfield/icon/adapter' {
  declare module.exports: any;
}

declare module '@material/textfield/icon/constants' {
  declare module.exports: any;
}

declare module '@material/textfield/icon/foundation' {
  declare module.exports: any;
}

declare module '@material/textfield/icon/index' {
  declare module.exports: any;
}

declare module '@material/textfield/label/adapter' {
  declare module.exports: any;
}

declare module '@material/textfield/label/constants' {
  declare module.exports: any;
}

declare module '@material/textfield/label/foundation' {
  declare module.exports: any;
}

declare module '@material/textfield/label/index' {
  declare module.exports: any;
}

declare module '@material/textfield/outline/adapter' {
  declare module.exports: any;
}

declare module '@material/textfield/outline/constants' {
  declare module.exports: any;
}

declare module '@material/textfield/outline/foundation' {
  declare module.exports: any;
}

declare module '@material/textfield/outline/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/textfield/adapter.js' {
  declare module.exports: $Exports<'@material/textfield/adapter'>;
}
declare module '@material/textfield/bottom-line/adapter.js' {
  declare module.exports: $Exports<'@material/textfield/bottom-line/adapter'>;
}
declare module '@material/textfield/bottom-line/constants.js' {
  declare module.exports: $Exports<'@material/textfield/bottom-line/constants'>;
}
declare module '@material/textfield/bottom-line/foundation.js' {
  declare module.exports: $Exports<'@material/textfield/bottom-line/foundation'>;
}
declare module '@material/textfield/bottom-line/index.js' {
  declare module.exports: $Exports<'@material/textfield/bottom-line/index'>;
}
declare module '@material/textfield/constants.js' {
  declare module.exports: $Exports<'@material/textfield/constants'>;
}
declare module '@material/textfield/dist/mdc.textfield.js' {
  declare module.exports: $Exports<'@material/textfield/dist/mdc.textfield'>;
}
declare module '@material/textfield/dist/mdc.textfield.min.js' {
  declare module.exports: $Exports<'@material/textfield/dist/mdc.textfield.min'>;
}
declare module '@material/textfield/foundation.js' {
  declare module.exports: $Exports<'@material/textfield/foundation'>;
}
declare module '@material/textfield/helper-text/adapter.js' {
  declare module.exports: $Exports<'@material/textfield/helper-text/adapter'>;
}
declare module '@material/textfield/helper-text/constants.js' {
  declare module.exports: $Exports<'@material/textfield/helper-text/constants'>;
}
declare module '@material/textfield/helper-text/foundation.js' {
  declare module.exports: $Exports<'@material/textfield/helper-text/foundation'>;
}
declare module '@material/textfield/helper-text/index.js' {
  declare module.exports: $Exports<'@material/textfield/helper-text/index'>;
}
declare module '@material/textfield/icon/adapter.js' {
  declare module.exports: $Exports<'@material/textfield/icon/adapter'>;
}
declare module '@material/textfield/icon/constants.js' {
  declare module.exports: $Exports<'@material/textfield/icon/constants'>;
}
declare module '@material/textfield/icon/foundation.js' {
  declare module.exports: $Exports<'@material/textfield/icon/foundation'>;
}
declare module '@material/textfield/icon/index.js' {
  declare module.exports: $Exports<'@material/textfield/icon/index'>;
}
declare module '@material/textfield/index' {
  declare module.exports: $Exports<'@material/textfield'>;
}
declare module '@material/textfield/index.js' {
  declare module.exports: $Exports<'@material/textfield'>;
}
declare module '@material/textfield/label/adapter.js' {
  declare module.exports: $Exports<'@material/textfield/label/adapter'>;
}
declare module '@material/textfield/label/constants.js' {
  declare module.exports: $Exports<'@material/textfield/label/constants'>;
}
declare module '@material/textfield/label/foundation.js' {
  declare module.exports: $Exports<'@material/textfield/label/foundation'>;
}
declare module '@material/textfield/label/index.js' {
  declare module.exports: $Exports<'@material/textfield/label/index'>;
}
declare module '@material/textfield/outline/adapter.js' {
  declare module.exports: $Exports<'@material/textfield/outline/adapter'>;
}
declare module '@material/textfield/outline/constants.js' {
  declare module.exports: $Exports<'@material/textfield/outline/constants'>;
}
declare module '@material/textfield/outline/foundation.js' {
  declare module.exports: $Exports<'@material/textfield/outline/foundation'>;
}
declare module '@material/textfield/outline/index.js' {
  declare module.exports: $Exports<'@material/textfield/outline/index'>;
}
