// flow-typed signature: 17ca3e9f29d5ada9fd8f69f7e4a4e73b
// flow-typed version: <<STUB>>/@material/theme_v^0.25.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/theme' {
  declare module.exports: any;
}
