// flow-typed signature: 94e93d8ab3b1e67403c1cc88f13c27ab
// flow-typed version: <<STUB>>/@material/theme_v^0.33.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/theme' {
  declare module.exports: any;
}
