// flow-typed signature: 6b099ab0b39b8e90bed73deb61021ae1
// flow-typed version: <<STUB>>/@material/theme_v^0.28.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/theme' {
  declare module.exports: any;
}
