// flow-typed signature: 475936b2d081d0ef4c7d0f05ff132f2e
// flow-typed version: <<STUB>>/@material/typography_v^0.28.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/typography'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/typography' {
  declare module.exports: any;
}
