// flow-typed signature: a915b4d4b25548c380746dfb658b5b86
// flow-typed version: <<STUB>>/@material/typography_v^0.3.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/typography'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/typography' {
  declare module.exports: any;
}
