// flow-typed signature: d6fb04af91f18dac71f95a4b79f16158
// flow-typed version: <<STUB>>/@material/typography_v^0.34.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/typography'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/typography' {
  declare module.exports: any;
}
